version: '2'
services:
  ibam-app:
    image: ibam
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ibam-postgresql:5432/IBAM
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8088:8088
  ibam-postgresql:
    extends:
      file: postgresql.yml
      service: ibam-postgresql
